### ISSUE TITLE
Needed modules TODO

### ISSUE THREAD

**Issue by rafelafrance** [rafelafrance/PowerRANGES#1]
This is an abbreviated list of modules that I need to write. Note that each trait requires 3 actual modules, the parser itself, the term CSV, and the tests. Some of this has been written before, so it's not nearly as bad as it looks.

- [x] pipeline (Needs slight modifications for every new trait.)
- [x] base parser
- [x] base length
- [x] body_mass
- [x] delete
- [x] ear_length
- [x] embryo_count
- [x] embryo_length
- [x] forearm_length
- [x] gonad_size
- [x] hind_foot_length
- [x] lactation_state
- [x] life_stage
- [x] mammary_count
- [x] mammary_state
- [x] nipple_count
- [x] nipple_state
- [x] ovaries_size
- [x] ovaries_state
- [x] placental_scar_count
- [x] placental_scar_state
- [x] pregnancy_state
- [x] sex
- [x] shorthand lengths
- [x] shorthand female states
- [x] tail_length
- [x] testes_size
- [x] testes_state
- [x] thumb_length
- [x] tibia_length
- [x] total_length
- [x] tragus_length
- [x] vagina_state
- [x] HTML output (Is critical for QA)
- [x] CSV output (people like these for analysis)
